### ISSUE TITLE
Click Options has errors

### ISSUE THREAD

**Issue by phanngochanh** [cleversoft/ztvirtuemarter#40]
There is an Options Button in backend component. When you press that, the error shows up.
"Fatal error: Call to a member function getFieldsets() on a non-object in D:\xampp\htdocs\car\administrator\components\com_config\view\component\html.php on line 57"

**Comment by kharol** [comment]
Fatal error: Call to a member function getFieldsets() on a non-object in /var/www/****/administrator/components/com_config/view/component/html.php on line 57
Component: JUX Real Estate
Joomla: Joomla! 3.5.1 Stable
